Repository Teemo-Wanted/GIS_Restaurant_Service, pull requests merged in 2023-11, with the labels that each got.

#2 [Feat] 회원가입, 로그인 기능 구현
  src/main/generated/com/wanted/restaurant/boundedContext/member/entity/QMember.java
  src/main/java/com/wanted/restaurant/base/config/AsyncConfig.java
  src/main/java/com/wanted/restaurant/base/config/QueryDslConfig.java
  src/main/java/com/wanted/restaurant/base/config/SwaggerConfig.java
  src/main/java/com/wanted/restaurant/base/jwt/JwtProvider.java
  src/main/java/com/wanted/restaurant/base/rsData/RsData.java
  src/main/java/com/wanted/restaurant/boundedContext/email/service/EmailService.java
  src/main/java/com/wanted/restaurant/boundedContext/initData/NotProd.java
  src/main/java/com/wanted/restaurant/boundedContext/member/controller/MemberController.java
  src/main/java/com/wanted/restaurant/boundedContext/member/entity/AlarmType.java
  src/main/java/com/wanted/restaurant/boundedContext/member/entity/Member.java
  src/main/java/com/wanted/restaurant/boundedContext/member/repository/MemberRepository.java
  src/main/java/com/wanted/restaurant/boundedContext/member/service/MemberService.java
  src/main/java/com/wanted/restaurant/util/Ut.java
  src/test/java/com/wanted/restaurant/base/jwt/JwtTests.java
  src/test/java/com/wanted/restaurant/boundedContext/member/controller/MemberControllerTests.java
Labels: enhancement

#15 [Feat] 사용자 정보 업데이트, 정보 확인, 로그인 기능 구현
  src/main/generated/com/wanted/restaurant/boundedContext/restaurant/entity/QRestaurant.java
  src/main/generated/com/wanted/restaurant/boundedContext/sigungu/entity/QSigungu.java
  src/main/java/com/wanted/restaurant/base/config/MvcConfig.java
  src/main/java/com/wanted/restaurant/base/config/SwaggerConfig.java
  src/main/java/com/wanted/restaurant/base/exceptionHandler/ApiGlobalExceptionHandler.java
  src/main/java/com/wanted/restaurant/base/exceptionHandler/AuthenticationException.java
  src/main/java/com/wanted/restaurant/base/interceptor/AuthorizationInterceptor.java
  src/main/java/com/wanted/restaurant/base/interceptor/AuthorizationTestController.java
  src/main/java/com/wanted/restaurant/base/resolver/LoginMember.java
  src/main/java/com/wanted/restaurant/base/resolver/LoginMemberContext.java
  src/main/java/com/wanted/restaurant/base/resolver/LoginUser.java
  src/main/java/com/wanted/restaurant/base/resolver/LoginUserResolver.java
  src/main/java/com/wanted/restaurant/boundedContext/initData/NotProd.java
  src/main/java/com/wanted/restaurant/boundedContext/member/controller/MemberController.java
  src/main/java/com/wanted/restaurant/boundedContext/member/entity/Member.java
  src/main/java/com/wanted/restaurant/boundedContext/member/service/MemberService.java
  src/main/java/com/wanted/restaurant/boundedContext/sigungu/repository/SigunguRepository.java
  src/main/java/com/wanted/restaurant/boundedContext/sigungu/service/SigunguService.java
  src/test/java/com/wanted/restaurant/boundedContext/member/controller/MemberControllerTests.java
Labels: enhancement

#18 [Feat] 디스코드 채팅방 웹훅 보내어 자동으로 식당 추천기능
  build.gradle
  src/main/java/com/wanted/restaurant/base/config/MvcConfig.java
  src/main/java/com/wanted/restaurant/boundedContext/discord/EventController.java
  src/main/java/com/wanted/restaurant/boundedContext/discord/WebHookService.java
  src/main/java/com/wanted/restaurant/boundedContext/initData/NotProd.java
  src/main/java/com/wanted/restaurant/boundedContext/member/repository/MemberRepository.java
  src/main/java/com/wanted/restaurant/boundedContext/member/service/MemberService.java
  src/main/java/com/wanted/restaurant/boundedContext/restaurant/service/RestaurantService.java
  src/main/java/com/wanted/restaurant/util/Ut.java
  src/main/resources/application-secret.yml.template
Labels: enhancement

#20 [Feat] 데이터 갱신 기능 구현
  src/main/java/com/wanted/restaurant/boundedContext/restaurant/entity/Restaurant.java
  src/main/java/com/wanted/restaurant/boundedContext/restaurant/repository/RestaurantRepository.java
  src/main/java/com/wanted/restaurant/util/openAPI/OpenAPIJSONParser.java
  src/main/java/com/wanted/restaurant/util/openAPI/OpenAPIPipeline.java
  src/main/java/com/wanted/restaurant/util/scheduler/DataPipelineScheduler.java
Labels: enhancement

#23 [Fix] 식당 검색 쿼리 수정 및 초기 식당 데이터 받아오게 수정
  src/main/java/com/wanted/restaurant/boundedContext/initData/NotProd.java
  src/main/java/com/wanted/restaurant/boundedContext/restaurant/controller/RestaurantController.java
  src/main/java/com/wanted/restaurant/boundedContext/restaurant/repository/RestaurantRepository.java
  src/main/java/com/wanted/restaurant/boundedContext/restaurant/service/RestaurantService.java
  src/main/java/com/wanted/restaurant/boundedContext/sigungu/repository/SigunguRepository.java
  src/main/java/com/wanted/restaurant/boundedContext/sigungu/service/SigunguService.java
  src/test/java/com/wanted/restaurant/boundedContext/restaurant/controller/RestaurantControllerTest.java
  src/test/java/com/wanted/restaurant/boundedContext/restaurant/service/RestaurantServiceTest.java
Labels: bug

#25 [Feat] 식당 상세정보 조회
  src/main/generated/com/wanted/restaurant/boundedContext/evalutation/entity/QEvaluation.java
  src/main/java/com/wanted/restaurant/boundedContext/evalutation/dto/EvaluateRequestDto.java
  src/main/java/com/wanted/restaurant/boundedContext/evalutation/repository/EvaluationRepository.java
  src/main/java/com/wanted/restaurant/boundedContext/evalutation/service/EvaluationService.java
  src/main/java/com/wanted/restaurant/boundedContext/initData/NotProd.java
  src/main/java/com/wanted/restaurant/boundedContext/member/entity/Member.java
  src/main/java/com/wanted/restaurant/boundedContext/restaurant/controller/RestaurantController.java
  src/main/java/com/wanted/restaurant/boundedContext/restaurant/dto/RestaurantDetailDTO.java
  src/main/java/com/wanted/restaurant/boundedContext/restaurant/repository/RestaurantRepository.java
  src/main/java/com/wanted/restaurant/boundedContext/restaurant/service/RestaurantService.java
  src/test/java/com/wanted/restaurant/boundedContext/restaurant/controller/RestaurantControllerTest.java
Labels: enhancement

#27 [Feat] 식당 평점 정렬 기준 추가
  src/main/java/com/wanted/restaurant/boundedContext/evalutation/controller/EvaluationController.java
  src/main/java/com/wanted/restaurant/boundedContext/initData/NotProd.java
  src/main/java/com/wanted/restaurant/boundedContext/restaurant/controller/RestaurantController.java
  src/main/java/com/wanted/restaurant/boundedContext/restaurant/dto/RestaurantQuery.java
  src/main/java/com/wanted/restaurant/boundedContext/restaurant/dto/RestaurantResponse.java
  src/main/java/com/wanted/restaurant/boundedContext/restaurant/repository/RestaurantRepository.java
  src/main/java/com/wanted/restaurant/boundedContext/restaurant/service/RestaurantService.java
  src/test/java/com/wanted/restaurant/boundedContext/restaurant/controller/RestaurantControllerTest.java
  src/test/java/com/wanted/restaurant/boundedContext/restaurant/service/RestaurantServiceTest.java
Labels: enhancement

#31 [Docs] Swagger 설정 및 불필요 import 제거
  src/main/java/com/wanted/restaurant/base/config/SwaggerConfig.java
  src/main/java/com/wanted/restaurant/base/interceptor/AuthorizationTestController.java
  src/main/java/com/wanted/restaurant/base/resolver/LoginMember.java
  src/main/java/com/wanted/restaurant/base/rsData/RsData.java
  src/main/java/com/wanted/restaurant/boundedContext/discord/EventController.java
  src/main/java/com/wanted/restaurant/boundedContext/discord/WebHookService.java
  src/main/java/com/wanted/restaurant/boundedContext/evalutation/controller/EvaluationController.java
  src/main/java/com/wanted/restaurant/boundedContext/evalutation/dto/EvaluateResponseDto.java
  src/main/java/com/wanted/restaurant/boundedContext/evalutation/entity/Evaluation.java
  src/main/java/com/wanted/restaurant/boundedContext/evalutation/repository/EvaluationRepository.java
  src/main/java/com/wanted/restaurant/boundedContext/evalutation/service/EvaluationService.java
  src/main/java/com/wanted/restaurant/boundedContext/member/controller/MemberController.java
  src/main/java/com/wanted/restaurant/boundedContext/restaurant/controller/RestaurantController.java
  src/main/java/com/wanted/restaurant/boundedContext/restaurant/dto/RestaurantResponse.java
  src/main/java/com/wanted/restaurant/boundedContext/restaurant/entity/Restaurant.java
  src/main/java/com/wanted/restaurant/boundedContext/restaurant/service/RestaurantService.java
  src/main/java/com/wanted/restaurant/boundedContext/sigungu/repository/SigunguRepository.java
  src/main/java/com/wanted/restaurant/boundedContext/sigungu/service/SigunguService.java
  src/main/java/com/wanted/restaurant/util/openAPI/OpenAPIJSONParser.java
  src/main/java/com/wanted/restaurant/util/openAPI/OpenAPIPipeline.java
  src/main/java/com/wanted/restaurant/util/openAPI/OpenAPIReader.java
  src/main/java/com/wanted/restaurant/util/openAPI/dto/RestaurantOpenAPIDto.java
  src/main/java/com/wanted/restaurant/util/scheduler/DataPipelineScheduler.java
  src/test/java/com/wanted/restaurant/boundedContext/restaurant/controller/RestaurantControllerTest.java
  src/test/java/com/wanted/restaurant/boundedContext/restaurant/service/RestaurantServiceTest.java
  src/test/java/com/wanted/restaurant/util/openAPI/OpenAPIPipelineTest.java
Labels: documentation
